# Generated by Django 3.1.1 on 2020-09-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starbucks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
