# Generated by Django 3.1.1 on 2020-09-08 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starbucks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='drink',
        ),
    ]
