# Generated by Django 3.1.1 on 2020-09-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starbucks', '0002_auto_20200908_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='img_link',
            field=models.URLField(default=''),
        ),
    ]
